
server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  sql:
    init:
#      schema-locations:
#        - classpath:db/table.sql
#      data-locations:
#        - classpath:db/data.sql
      mode: embedded
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.naver.com
    port: 465
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          timeout: 5000
          ssl:
            trust: smtp.naver.com
            enable: true #반드시 필요 -> SSL 필요로 되어있으면

logging:
  level:
    '[fastcampus.group9.toyproject3]': DEBUG
    '[org.hibernate.type]': TRACE

mybatis:
  mapper-locations:
    - classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true